// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StdPerfomance.Core;

#nullable disable

namespace StdPerfomance.Core.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260430132633_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StdPerfomance.Core.Entities.StressLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StressLevels");
                });

            modelBuilder.Entity("StdPerfomance.Core.Entities.StudentScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExamScore")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SleepHours")
                        .HasColumnType("int");

                    b.Property<int>("SocialMediaHours")
                        .HasColumnType("int");

                    b.Property<int>("StressLevelId")
                        .HasColumnType("int");

                    b.Property<int>("StudyHours")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StressLevelId");

                    b.ToTable("StudentScores");
                });

            modelBuilder.Entity("StdPerfomance.Core.Entities.StudentScore", b =>
                {
                    b.HasOne("StdPerfomance.Core.Entities.StressLevel", "StressLevel")
                        .WithMany("StudentScores")
                        .HasForeignKey("StressLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StressLevel");
                });

            modelBuilder.Entity("StdPerfomance.Core.Entities.StressLevel", b =>
                {
                    b.Navigation("StudentScores");
                });
#pragma warning restore 612, 618
        }
    }
}
